programming_languages = [
    {'name': 'C', 'alt_name': 'c'},
    {'name': 'C++', 'alt_name': 'cpp'},
    {'name': 'Java', 'alt_name': 'java'},
    {'name': 'Python', 'alt_name': 'python'},
    {'name': 'PHP', 'alt_name': 'php'},
    {'name': 'JavaScript', 'alt_name': 'javascript'},
    {'name': 'TypeScript', 'alt_name': 'typescript'},
    {'name': 'C#', 'alt_name': 'csharp'},
    {'name': 'Ruby', 'alt_name': 'ruby'},
    {'name': 'Go', 'alt_name': 'go'},
    {'name': 'Swift', 'alt_name': 'swift'},
    {'name': 'Kotlin', 'alt_name': 'kotlin'},
    {'name': 'Rust', 'alt_name': 'rust'},
    {'name': 'HTML', 'alt_name': 'html'},
    {'name': 'CSS', 'alt_name': 'css'},
    {'name': 'SQL', 'alt_name': 'sql'},
    {'name': 'R', 'alt_name': 'r'},
    {'name': 'Shell', 'alt_name': 'shell'},
    {'name': 'Objective-C', 'alt_name': 'objective-c'},
    {'name': 'MATLAB', 'alt_name': 'matlab'},
    {'name': 'Perl', 'alt_name': 'perl'},
    {'name': 'Dart', 'alt_name': 'dart'},
    {'name': 'Scala', 'alt_name': 'scala'},
    {'name': 'Haskell', 'alt_name': 'haskell'},
    {'name': 'Lua', 'alt_name': 'lua'},
    {'name': 'Groovy', 'alt_name': 'groovy'}
]
